<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Nucid Services State
    |--------------------------------------------------------------------------
    |
    */
    'state' => env('NUCID_SERVICES_STATE', true),

    /*
    |--------------------------------------------------------------------------
    | Nucid Default Service
    |--------------------------------------------------------------------------
    |
    */
    'default' => env('NUCID_SERVICES_DEFAULT', 'frontend'),

    /*
    |--------------------------------------------------------------------------
    | Path to the base service directory
    |--------------------------------------------------------------------------
    | Relative to the Laravel base directory
    */
    'base_path' => env('NUCID_SERVICES_BASE_PATH', 'app'.DIRECTORY_SEPARATOR.'Services'),

    /*
    |--------------------------------------------------------------------------
    | Path to the domains directory
    |--------------------------------------------------------------------------
    | Relative to the Laravel base directory
    */
    'domains_path' => env('NUCID_SERVICES_DOMAINS_PATH', 'app'.DIRECTORY_SEPARATOR.'Domains'),

    /*
    |--------------------------------------------------------------------------
    | Nucid Services sub folders
    |--------------------------------------------------------------------------
    | Relative to the Nucid service directory
    */
    'routes_dir'      => env('NUCID_SERVICES_ROUTES_DIR', 'Routes'),
    'providers_dir'   => env('NUCID_SERVICES_PROVIDERS_DIR', 'Providers'),
    'controllers_dir' => env('NUCID_SERVICES_CONTROLLERS_DIR', 'Controllers'),
    'features_dir'    => env('NUCID_SERVICES_FEATURES_DIR', 'Features'),
    'resources_dir'   => env('NUCID_SERVICES_RESOURCES_DIR', 'Resources'),
    'requests_dir'    => env('NUCID_SERVICES_REQUESTS_DIR', 'Requests'),

    /*
    |--------------------------------------------------------------------------
    | Nucid Services file names
    |--------------------------------------------------------------------------
    | Paths are autogenerated
    */
    'routes_file'          => env('NUCID_SERVICES_ROUTES_FILE', 'routes.php'),
    'service_config_file'  => env('NUCID_SERVICES_SERVICE_CONFIG_FILE', 'service.php'),

    /*
    |--------------------------------------------------------------------------
    | Nucid Services
    |--------------------------------------------------------------------------
    |
    */
    'services' => [
        'frontend' => [
            'subdomain'          => null,
            'route_prefix'       => null,
            'relative_path'      => 'Frontend',
            'middleware'         => ['web'],
        ],
    ],
];
